from engine import config


def apply_config():
    global CONFIG_FILE, TOKEN, TOKEN_TRADE, TOKEN_HISTORY, ACCOUNT_ID, TICKERS_CONFIG, ACCOUNTS, LOG_ACCOUNT_NAME
    global UPDATE_DELAY, MODE, ANALYSIS_ONLY, REBUILD_STATE_ON_START, LOAD_HISTORY_ON_START
    global HISTORY_YEARS, REFRESH_HISTORY_ON_CHANGE
    global DASHBOARD_ENABLED, DASHBOARD_PATH, DASHBOARD_HOST, DASHBOARD_PORT, DASHBOARD_CMD
    global DASHBOARD_API_ENABLED, DASHBOARD_API_HOST, DASHBOARD_API_PORT
    global LOG_FILE, DETAILED_LOG_FILE, DETAILED_LOG_LEVEL
    global TMON_FIGI, TMON_REBALANCE_ENABLED, MAX_MARGIN, MIN_CASH_RESERVE, MAX_DAILY_CAPITAL_PERCENT
    global TRADING_START_TIME, TRADING_END_TIME, WEEKEND_TRADING_START_TIME, WEEKEND_TRADING_END_TIME
    global WEEKEND_LIMIT_ORDERS_START_TIME, DEFAULT_FIGI_TEMPLATE
    global TRAILING_GRID_MODE, MIN_PROFIT_STEP_PCT, COMMISSION_RATE, BUY_BASED_ON_AVG_PRICE
    global DEFAULT_BUY_BASE_MODE, DEFAULT_SELL_BASE_MODE, IGNORE_LIMITS_SHARES, IS_QUALIFIED_INVESTOR
    global CAPITAL_ALLOCATION, REBALANCE_TIME, ORDER_REFRESH_GRACE_SEC
    global BASE_DIR, BOT_ORDER_PREFIX, FIGI_FILE

    CONFIG_FILE = config.CONFIG_FILE
    TOKEN = config.TOKEN
    TOKEN_TRADE = getattr(config, "TOKEN_TRADE", None) or TOKEN
    TOKEN_HISTORY = getattr(config, "TOKEN_HISTORY", None) or TOKEN
    ACCOUNT_ID = config.ACCOUNT_ID
    TICKERS_CONFIG = config.TICKERS_CONFIG
    ACCOUNTS = getattr(config, "ACCOUNTS", [])
    LOG_ACCOUNT_NAME = ""

    UPDATE_DELAY = getattr(config, "ANALYSIS_INTERVAL", 60)
    MODE = getattr(config, "MODE", "LIFO")  # FIFO / LIFO
    ANALYSIS_ONLY = getattr(config, "ANALYSIS_ONLY", False)
    REBUILD_STATE_ON_START = getattr(config, "REBUILD_STATE_ON_START", True)
    LOAD_HISTORY_ON_START = getattr(config, "LOAD_HISTORY_ON_START", True)
    HISTORY_YEARS = getattr(config, "HISTORY_YEARS", 3)
    REFRESH_HISTORY_ON_CHANGE = getattr(config, "REFRESH_HISTORY_ON_CHANGE", True)

    DASHBOARD_ENABLED = getattr(config, "DASHBOARD_ENABLED", False)
    DASHBOARD_PATH = getattr(config, "DASHBOARD_PATH", "trading-desk-dashboard-main")
    DASHBOARD_HOST = getattr(config, "DASHBOARD_HOST", "127.0.0.1")
    DASHBOARD_PORT = getattr(config, "DASHBOARD_PORT", 5173)
    DASHBOARD_CMD = getattr(config, "DASHBOARD_CMD", "npm run dev")
    DASHBOARD_API_ENABLED = getattr(config, "DASHBOARD_API_ENABLED", True)
    DASHBOARD_API_HOST = getattr(config, "DASHBOARD_API_HOST", "127.0.0.1")
    DASHBOARD_API_PORT = getattr(config, "DASHBOARD_API_PORT", 8000)

    LOG_FILE = getattr(config, "LOG_FILE", "bot_logs.log")
    DETAILED_LOG_FILE = getattr(config, "DETAILED_LOG_FILE", None)
    DETAILED_LOG_LEVEL = getattr(config, "DETAILED_LOG_LEVEL", "DEBUG")

    TMON_FIGI = getattr(config, "TMON_FIGI", None)
    TMON_REBALANCE_ENABLED = getattr(config, "TMON_REBALANCE_ENABLED", True)
    MAX_MARGIN = getattr(config, "MAX_MARGIN", 0)
    MIN_CASH_RESERVE = getattr(config, "MIN_CASH_RESERVE", 0)
    MAX_DAILY_CAPITAL_PERCENT = getattr(config, "MAX_DAILY_CAPITAL_PERCENT", 1.0)

    # Торговое время
    TRADING_START_TIME = getattr(config, "TRADING_START_TIME", "06:58")
    TRADING_END_TIME = getattr(config, "TRADING_END_TIME", "23:43")
    WEEKEND_TRADING_START_TIME = getattr(config, "WEEKEND_TRADING_START_TIME", "02:00")  # NEW
    WEEKEND_TRADING_END_TIME = getattr(config, "WEEKEND_TRADING_END_TIME", "23:59")      # NEW
    WEEKEND_LIMIT_ORDERS_START_TIME = getattr(config, "WEEKEND_LIMIT_ORDERS_START_TIME", "02:00")

    TRAILING_GRID_MODE = getattr(config, "TRAILING_GRID_MODE", True)
    MIN_PROFIT_STEP_PCT = getattr(config, "MIN_PROFIT_STEP_PCT", 0.0)
    COMMISSION_RATE = getattr(config, "COMMISSION_RATE", 0.0005)
    BUY_BASED_ON_AVG_PRICE = getattr(config, "BUY_BASED_ON_AVG_PRICE", False)
    DEFAULT_BUY_BASE_MODE = getattr(config, "DEFAULT_BUY_BASE_MODE", "last")
    DEFAULT_SELL_BASE_MODE = getattr(config, "DEFAULT_SELL_BASE_MODE", "last")
    IGNORE_LIMITS_SHARES = getattr(config, "IGNORE_LIMITS_SHARES", False)
    IS_QUALIFIED_INVESTOR = getattr(config, "IS_QUALIFIED_INVESTOR", False)
    CAPITAL_ALLOCATION = getattr(
        config,
        "CAPITAL_ALLOCATION",
        {"share": 0.5, "bond": 0.5, "futures": 0.0, "fund": 0.0},
    )
    REBALANCE_TIME = getattr(config, "REBALANCE_TIME", None)
    ORDER_REFRESH_GRACE_SEC = getattr(config, "ORDER_REFRESH_GRACE_SEC", 120)
    DEFAULT_FIGI_TEMPLATE = getattr(config, "DEFAULT_FIGI_TEMPLATE", {})

    BASE_DIR = config.BASE_DIR
    BOT_ORDER_PREFIX = "bot"
    FIGI_FILE = "data/figi_names.json"


apply_config()

# ⚠️ ВАЖНО: добавляем новые переменные в __all__
__all__ = [
    "CONFIG_FILE",
    "TOKEN",
    "TOKEN_TRADE",
    "TOKEN_HISTORY",
    "ACCOUNT_ID",
    "TICKERS_CONFIG",
    "ACCOUNTS",
    "LOG_ACCOUNT_NAME",
    "UPDATE_DELAY",
    "MODE",
    "ANALYSIS_ONLY",
    "REBUILD_STATE_ON_START",
    "LOAD_HISTORY_ON_START",
    "HISTORY_YEARS",
    "REFRESH_HISTORY_ON_CHANGE",
    "LOG_FILE",
    "DETAILED_LOG_FILE",
    "DETAILED_LOG_LEVEL",
    "DASHBOARD_ENABLED",
    "DASHBOARD_PATH",
    "DASHBOARD_HOST",
    "DASHBOARD_PORT",
    "DASHBOARD_CMD",
    "DASHBOARD_API_ENABLED",
    "DASHBOARD_API_HOST",
    "DASHBOARD_API_PORT",
    "TMON_FIGI",
    "TMON_REBALANCE_ENABLED",
    "MAX_MARGIN",
    "MIN_CASH_RESERVE",
    "MAX_DAILY_CAPITAL_PERCENT",
    "TRADING_START_TIME",
    "TRADING_END_TIME",
    "WEEKEND_TRADING_START_TIME",  # NEW
    "WEEKEND_TRADING_END_TIME",    # NEW
    "WEEKEND_LIMIT_ORDERS_START_TIME",
    "TRAILING_GRID_MODE",
    "MIN_PROFIT_STEP_PCT",
    "COMMISSION_RATE",
    "BUY_BASED_ON_AVG_PRICE",
    "DEFAULT_BUY_BASE_MODE",
    "DEFAULT_SELL_BASE_MODE",
    "IGNORE_LIMITS_SHARES",
    "IS_QUALIFIED_INVESTOR",
    "CAPITAL_ALLOCATION",
    "REBALANCE_TIME",
    "ORDER_REFRESH_GRACE_SEC",
    "DEFAULT_FIGI_TEMPLATE",
    "BASE_DIR",
    "BOT_ORDER_PREFIX",
    "FIGI_FILE",
]
